# builds web/evolab.py, the single file browser version.
#
# pyscript only runs ONE file (the <script type="py-game">), so this glues
# all the modules together in dependency order, cuts out the local imports
# (everything ends up in one big namespace anyway) and sticks the browser
# startup code on the end. run it again after you change anything:
#
#     .venv/bin/python web/build.py
#
# yes the order of MODULES matters, ask me how i know

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# DO NOT reorder this. it goes parents before children
MODULES = [
    ("ui.theme", "ui/theme.py"),
    ("ui.fonts", "ui/fonts.py"),
    ("simulation.genome", "simulation/genome.py"),
    ("simulation.food", "simulation/food.py"),
    ("simulation.types", "simulation/types.py"),
    ("simulation.spatial", "simulation/spatial.py"),
    ("simulation.ecosystem", "simulation/ecosystem.py"),
    ("rendering.orbs", "rendering/orbs.py"),
    ("ui.widgets", "ui/widgets.py"),
    ("ui.charts", "ui/charts.py"),
    ("ui.inspector", "ui/inspector.py"),
    ("ui.hud", "ui/hud.py"),
    ("rendering.renderer", "rendering/renderer.py"),
    ("main", "main.py"),
]

LOCAL_IMPORT = re.compile(r"^from (\.|ui(\s|\.|$)|simulation(\s|\.|$)|rendering(\s|\.|$))")


def strip_local_imports(text: str) -> str:
    # delete "from .x import y" style lines. the bracket counting is for
    # the multi line ones like "from .genome import (\n  a,\n  b,\n)"
    lines = text.splitlines()
    out = []
    i = 0
    while i < len(lines):
        s = lines[i].strip()
        if LOCAL_IMPORT.match(s):
            depth = lines[i].count("(") - lines[i].count(")")
            while depth > 0:
                i += 1
                depth += lines[i].count("(") - lines[i].count(")")
            i += 1
            continue
        out.append(lines[i])
        i += 1
    return "\n".join(out)


def main() -> None:
    parts = []
    for name, rel in MODULES:
        src = (ROOT / rel).read_text(encoding="utf-8")
        if name == "main":
            # take the __main__ guard out, the browser entry at the bottom
            # of the file starts the game instead
            guard = 'if __name__ == "__main__":\n    raise SystemExit(asyncio.run(main()))\n'
            src = src.replace(guard, "")
        src = strip_local_imports(src)
        # theme is inlined at the very top so every "theme.RED" has to
        # become just "RED"
        src = re.sub(r"\btheme\.([A-Za-z_]\w*)", r"\1", src)
        parts.append(f"\n\n# ===== {rel} =====\n" + src.strip("\n") + "\n")

    header = (
        "# EvoLab web build. GENERATED by web/build.py - do not edit this\n"
        "# file, edit the real modules and run the builder again\n"
    )
    entry = """

# --- web entry ------------------------------------------------------------
# pyscript runs this in an async context so we start main() by hand:
# as a task if there is already a loop running, otherwise asyncio.run
try:
    asyncio.get_running_loop()
    asyncio.create_task(main())
except RuntimeError:
    asyncio.run(main())

try:  # just hides the loading text once the game is actually running
    from pyscript import window as _win

    _status = _win.document.getElementById("status")
    if _status:
        _status.style.display = "none"
except Exception:
    pass
"""
    out = ROOT / "web" / "evolab.py"
    out.write_text(header + "".join(parts) + entry, encoding="utf-8")
    print(f"wrote web/evolab.py ({out.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
