"""Build web/evolab.py — a single-file web build of EvoLab for PyScript.

PyScript's <script type="py-game"> executes one entry file, so this
concatenates the project modules in dependency order, drops the local
imports (every name lands in one shared namespace) and appends the web
entry point. Re-run after changing any source module:

    .venv/bin/python web/build.py
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# (module name, source file) in dependency order
MODULES = [
    ("ui.theme", "ui/theme.py"),
    ("ui.fonts", "ui/fonts.py"),
    ("simulation.genome", "simulation/genome.py"),
    ("simulation.food", "simulation/food.py"),
    ("simulation.types", "simulation/types.py"),
    ("simulation.spatial", "simulation/spatial.py"),
    ("simulation.ecosystem", "simulation/ecosystem.py"),
    ("rendering.orbs", "rendering/orbs.py"),
    ("ui.widgets", "ui/widgets.py"),
    ("ui.charts", "ui/charts.py"),
    ("ui.inspector", "ui/inspector.py"),
    ("ui.hud", "ui/hud.py"),
    ("rendering.renderer", "rendering/renderer.py"),
    ("main", "main.py"),
]

LOCAL_IMPORT = re.compile(r"^from (\.|ui(\s|\.|$)|simulation(\s|\.|$)|rendering(\s|\.|$))")


def strip_local_imports(text: str) -> str:
    """Drop `from .x` / `from ui.x` style imports (single and parenthesized)."""
    lines = text.splitlines()
    out = []
    i = 0
    while i < len(lines):
        s = lines[i].strip()
        if LOCAL_IMPORT.match(s):
            depth = lines[i].count("(") - lines[i].count(")")
            while depth > 0:
                i += 1
                depth += lines[i].count("(") - lines[i].count(")")
            i += 1
            continue
        out.append(lines[i])
        i += 1
    return "\n".join(out)


def main() -> None:
    parts = []
    for name, rel in MODULES:
        src = (ROOT / rel).read_text(encoding="utf-8")
        if name == "main":
            # The web entry appended below starts the game.
            guard = 'if __name__ == "__main__":\n    raise SystemExit(asyncio.run(main()))\n'
            src = src.replace(guard, "")
        src = strip_local_imports(src)
        # ui.theme is inlined at the top; unwrap its attribute references.
        src = re.sub(r"\btheme\.([A-Za-z_]\w*)", r"\1", src)
        parts.append(f"\n\n# ===== {rel} =====\n" + src.strip("\n") + "\n")

    header = (
        '"""EvoLab web build — generated by web/build.py, do not edit by hand.\n'
        "\n"
        "Single-file concatenation of the project modules so PyScript's\n"
        "<script type=\"py-game\"> can execute one entry file. Re-run\n"
        "`python web/build.py` after changing any source module.\n"
        '"""\n'
    )
    entry = """

# --- web entry ------------------------------------------------------------
# PyScript executes this file as a script (in an async context), so the
# game is started explicitly: as a task if a loop is already running, or
# via asyncio.run otherwise.
try:
    asyncio.get_running_loop()
    asyncio.create_task(main())
except RuntimeError:
    asyncio.run(main())

try:  # cosmetic: hide the loading line once the game is up
    from pyscript import window as _win

    _status = _win.document.getElementById("status")
    if _status:
        _status.style.display = "none"
except Exception:
    pass
"""
    out = ROOT / "web" / "evolab.py"
    out.write_text(header + "".join(parts) + entry, encoding="utf-8")
    print(f"wrote web/evolab.py ({out.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
