# builds web/evolab.py, the single file browser version.
#
# pyscript only runs ONE file (the <script type="py-game">), so this glues
# all the modules together in dependency order, cuts out the local imports
# (everything ends up in one big namespace anyway) and sticks the browser
# startup code on the end. run it again after you change anything:
#
#     .venv/bin/python web/build.py
#
# yes the order of MODULES matters, ask me how i know

import ast
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# DO NOT reorder this. it goes parents before children
MODULES = [
    ("ui.theme", "ui/theme.py"),
    ("ui.fonts", "ui/fonts.py"),
    ("simulation.genome", "simulation/genome.py"),
    ("simulation.food", "simulation/food.py"),
    ("simulation.types", "simulation/types.py"),
    ("simulation.spatial", "simulation/spatial.py"),
    ("simulation.snapshot", "simulation/snapshot.py"),
    ("simulation.ecosystem", "simulation/ecosystem.py"),
    ("rendering.orbs", "rendering/orbs.py"),
    ("ui.widgets", "ui/widgets.py"),
    ("ui.charts", "ui/charts.py"),
    ("ui.inspector", "ui/inspector.py"),
    ("ui.hud", "ui/hud.py"),
    ("rendering.renderer", "rendering/renderer.py"),
    ("main", "main.py"),
]

LOCAL_IMPORT = re.compile(r"^from (\.|ui(\s|\.|$)|simulation(\s|\.|$)|rendering(\s|\.|$))")
ANY_IMPORT = re.compile(r"^from\s+(\.*)([A-Za-z_][\w.]*)?\s+import", re.M)

# packages whose modules get glued together
PACKAGES = ("ui", "simulation", "rendering")


def check_modules() -> None:
    # every local import has to point at a file that is in MODULES.
    # forgetting one is invisible until the exact code path that uses it
    # runs, and then the game just dies in the browser (the time machine
    # did this for weeks: snapshot.py was never in the list)
    have = {rel for _, rel in MODULES}
    missing = []
    for _, rel in MODULES:
        text = (ROOT / rel).read_text(encoding="utf-8")
        for m in ANY_IMPORT.finditer(text):
            dots, mod = m.group(1), m.group(2) or ""
            if not dots and mod.split(".")[0] not in PACKAGES:
                continue  # a real library, not ours
            if not dots and "." not in mod:
                continue  # "from ui import theme" style, checked below
            base = Path(rel).parent if dots else Path()
            target = base / (mod.replace(".", "/") + ".py")
            if str(target) in have:
                continue
            if any(h.startswith(mod.replace(".", "/") + "/") for h in have):
                continue
            missing.append(f"  {rel} imports {m.group(0).strip()} -> {target}")
    if missing:
        raise SystemExit(
            "these modules are imported but not in MODULES, the web build "
            "would break at runtime:\n" + "\n".join(missing)
        )


def strip_local_imports(text: str) -> str:
    # delete "from .x import y" style lines. the bracket counting is for
    # the multi line ones like "from .genome import (\n  a,\n  b,\n)"
    #
    # anything renamed on the way in ("import capture as capture_snapshot")
    # has to become a plain assignment, otherwise the aliased name never
    # exists and the build dies the first time that code path runs
    lines = text.splitlines()
    out = []
    i = 0
    while i < len(lines):
        s = lines[i].strip()
        if LOCAL_IMPORT.match(s):
            start = i
            depth = lines[i].count("(") - lines[i].count(")")
            i += 1
            while depth > 0:
                depth += lines[i].count("(") - lines[i].count(")")
                i += 1
            statement = "\n".join(lines[start:i])
            try:
                node = ast.parse(statement).body[0]
            except SyntaxError:
                continue
            for alias in getattr(node, "names", []):
                if alias.asname:
                    out.append(f"{alias.asname} = {alias.name}")
            continue
        out.append(lines[i])
        i += 1
    return "\n".join(out)


def main() -> None:
    check_modules()
    parts = []
    for name, rel in MODULES:
        src = (ROOT / rel).read_text(encoding="utf-8")
        if name == "main":
            # take the __main__ guard out, the browser entry at the bottom
            # of the file starts the game instead
            guard = 'if __name__ == "__main__":\n    raise SystemExit(asyncio.run(main()))\n'
            src = src.replace(guard, "")
        src = strip_local_imports(src)
        # theme is inlined at the very top so every "theme.RED" has to
        # become just "RED"
        src = re.sub(r"\btheme\.([A-Za-z_]\w*)", r"\1", src)
        parts.append(f"\n\n# ===== {rel} =====\n" + src.strip("\n") + "\n")

    header = (
        "# EvoLab web build. GENERATED by web/build.py - do not edit this\n"
        "# file, edit the real modules and run the builder again\n"
    )
    entry = """

# --- web entry ------------------------------------------------------------
# pyscript runs this in an async context so we start main() by hand
def _show_error(text):
    # put the traceback on the page. if this thing dies silently in a
    # browser there is nothing to go on, which cost me an hour once
    print(text)
    try:
        from pyscript import window as _win

        box = _win.document.getElementById("err")
        if box:
            box.style.display = "block"
            box.textContent = text
    except Exception:
        pass


async def _start():
    try:
        await main()
    except BaseException:
        import traceback

        _show_error(traceback.format_exc())


def _hide_loading():
    try:
        from pyscript import window as _win

        _status = _win.document.getElementById("status")
        if _status:
            _status.style.display = "none"
    except Exception:
        pass


try:
    asyncio.get_running_loop()
    asyncio.create_task(_start())
    _hide_loading()
except RuntimeError:
    _hide_loading()
    asyncio.run(_start())
"""
    out = ROOT / "web" / "evolab.py"
    out.write_text(header + "".join(parts) + entry, encoding="utf-8")
    print(f"wrote web/evolab.py ({out.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
