#!/bin/sh
# Pushes the browser version to the gh-pages branch.
#
# evolab.py is generated by build.py so it isnt kept in git - this builds it
# fresh and pushes just the two site files over. If you have git subtree you
# can use that instead, this is just the version that works here.
set -e
cd "$(dirname "$0")/.."

PY=.venv/bin/python
[ -x "$PY" ] || PY=python3
"$PY" web/build.py

html=$(git hash-object -w web/index.html)
game=$(git hash-object -w web/evolab.py)
tree=$(printf '100644 blob %s\tindex.html\n100644 blob %s\tevolab.py\n' \
    "$html" "$game" | git mktree)

parent=$(git rev-parse --verify -q origin/gh-pages || true)
if [ -n "$parent" ]; then
    commit=$(git commit-tree "$tree" -p "$parent" -m "deploy site")
else
    commit=$(git commit-tree "$tree" -m "deploy site")
fi

git push origin "$commit:refs/heads/gh-pages"
echo "pushed $commit to gh-pages"
