"""EvoLab web build — generated by web/build.py, do not edit by hand.

Single-file concatenation of the project modules so PyScript's
<script type="py-game"> can execute one entry file. Re-run
`python web/build.py` after changing any source module.
"""


# ===== ui/theme.py =====
"""Shared color palette — the "scientific research lab" dark theme."""

BG = (11, 15, 20)          # window background
PANEL = (16, 22, 29)       # chrome panels
PANEL_BORDER = (29, 39, 51)
TEXT = (203, 213, 225)
TEXT_DIM = (100, 116, 139)
ACCENT = (52, 211, 153)    # organism green / interactive accent
PREDATOR = (248, 113, 113)  # predator organism — warm red, the danger read
HEADING = (32, 140, 102)   # prey heading tick, dimmer than the dot
HEADING_PRED = (160, 60, 60)  # predator heading tick
FOOD = (212, 175, 55)       # food item — amber, distinct from organism green
GRID_ALPHA = 14            # lab-plate grid line alpha (0-255)


# ===== simulation/genome.py =====
"""Heritable traits: the genome and its mapping to visible phenotypes.

Every trait is a float in [0, 1]. Higher is not always better — each
trait carries a tradeoff enforced in `energy_drain_per_s` and friends.

Wired into the simulation right now: speed, size, metabolism, lifespan,
efficiency, vision (sensing), fertility (reproduction). Still dormant:
aggression (predation).
"""

import random
from dataclasses import dataclass

TRAIT_NAMES = (
    "speed",
    "size",
    "vision",
    "metabolism",
    "fertility",
    "lifespan",
    "aggression",
    "efficiency",
)


@dataclass(slots=True)
class Genome:
    speed: float  # faster movement, higher movement upkeep
    size: float  # bigger body, higher upkeep, bigger target
    vision: float  # sensing range (food/predators) — dormant
    metabolism: float  # base energy burn rate
    fertility: float  # reproduction readiness — dormant
    lifespan: float  # max age in seconds
    aggression: float  # predator behavior — dormant
    efficiency: float  # lowers every energy cost


def random_genome() -> Genome:
    return Genome(*(random.random() for _ in TRAIT_NAMES))


# --- genetics --------------------------------------------------------

def crossover(a: Genome, b: Genome) -> Genome:
    """Uniform crossover: each trait is copied from a random parent."""
    return Genome(
        **{n: random.choice((getattr(a, n), getattr(b, n))) for n in TRAIT_NAMES}
    )


def mutate(g: Genome, rate: float) -> Genome:
    """Per-trait point mutation: with probability `rate`, nudge the trait.

    The nudge is a Gaussian step clamped to [0, 1]. `rate` is the
    probability per trait (the user-facing mutation slider).
    """
    if rate <= 0.0:
        return g
    vals = {}
    for n in TRAIT_NAMES:
        v = getattr(g, n)
        if random.random() < rate:
            v = max(0.0, min(1.0, v + random.gauss(0.0, 0.15)))
        vals[n] = v
    return Genome(**vals)


# --- phenotype mapping (pure geometry) --------------------------------

def body_radius_px(size: float) -> float:
    return 2.0 + size * 6.0  # 2..8 px


def move_speed_px(genome: Genome) -> float:
    return 10.0 + genome.speed * 60.0  # 10..70 px/s


# ===== simulation/food.py =====
"""Food — the resource organisms compete for."""

from dataclasses import dataclass


@dataclass(slots=True)
class Food:
    id: int
    x: float
    y: float
    energy: float


# ===== simulation/types.py =====
from dataclasses import dataclass



@dataclass(slots=True)
class Organism:
    """A living organism with a heritable genome.

    Energy drains every tick (metabolism + movement + body upkeep);
    hitting zero means starvation death. Ageing past the genome's
    lifespan means natural death.
    """

    id: int
    x: float
    y: float
    heading: float  # movement direction in radians
    genome: Genome
    energy: float
    age: float
    generation: int = 1  # genealogical generation (initial stock is 1)
    readiness: float = 0.0  # accumulates to 1.0, gated by fertility
    target: Food | None = None  # food currently being chased
    last_sense: float = 0.0  # sim time of the last food scan
    # Predation:
    dead: bool = False  # flagged when removed by any cause (swept each tick)
    prey_target: "Organism | None" = None  # prey being hunted (predators only)
    last_hunt: float = 0.0  # sim time of the last prey scan
    danger: "Organism | None" = None  # nearest threat sensed (higher aggression)
    fleeing: bool = False  # sprinting away this tick (resets each tick)
    on_hunt: bool = False  # hunting this hunger span (aggression-weighted)


# ===== simulation/spatial.py =====
"""Spatial hash grid: fast neighbor queries on the toroidal world.

Rebuilt once per tick (cheap: one dict insert per item). Queries scan
only the cells a circle overlaps, so cost is independent of population
size for small radii — this is what makes local mating (and later,
predation) affordable at large populations.
"""

import math


class SpatialGrid:
    def __init__(self, width: int, height: int, cell: int = 64) -> None:
        self.width = width
        self.height = height
        self.cell = cell
        self.cols = max(1, math.ceil(width / cell))
        self.rows = max(1, math.ceil(height / cell))
        self.cells: dict[tuple[int, int], list] = {}

    def rebuild(self, items: list) -> None:
        self.cells.clear()
        for it in items:
            key = (int(it.x) // self.cell, int(it.y) // self.cell)
            bucket = self.cells.get(key)
            if bucket is None:
                self.cells[key] = [it]
            else:
                bucket.append(it)

    def within(self, x: float, y: float, radius: float) -> list:
        """Items within `radius` of (x, y), toroidal-aware."""
        c = self.cell
        half_w, half_h = self.width / 2, self.height / 2
        r2 = radius * radius
        x0 = int((x - radius) // c)
        x1 = int((x + radius) // c)
        y0 = int((y - radius) // c)
        y1 = int((y + radius) // c)

        out = []
        for cx in range(x0, x1 + 1):
            for cy in range(y0, y1 + 1):
                bucket = self.cells.get((cx % self.cols, cy % self.rows))
                if not bucket:
                    continue
                for it in bucket:
                    dx = it.x - x
                    if dx > half_w:
                        dx -= self.width
                    elif dx < -half_w:
                        dx += self.width
                    if dx * dx > r2:
                        continue
                    dy = it.y - y
                    if dy > half_h:
                        dy -= self.height
                    elif dy < -half_h:
                        dy += self.height
                    if dx * dx + dy * dy <= r2:
                        out.append(it)
        return out


# ===== simulation/ecosystem.py =====
"""EvoLab — artificial ecosystem simulator."""

import math
import random
from dataclasses import dataclass



@dataclass
class WorldConfig:
    width: int
    height: int
    organisms: int  # starting organism count
    wander_turn_rate: float  # how eagerly a creature changes direction (rad/s)

    # --- energy ---------------------------------------------------------
    max_energy: float = 100.0
    # drain/s = (base + range*metabolism) * (1 + speed_cost*speed + size_cost*size)
    #          * (1 - efficiency_saving*efficiency)
    base_metabolism: float = 0.30  # energy/s at minimal traits
    metabolism_range: float = 0.55  # extra burn from the metabolism trait
    speed_cost: float = 0.6  # upkeep multiplier weight for speed trait
    size_cost: float = 0.8  # upkeep multiplier weight for size trait
    efficiency_saving: float = 0.5  # fraction of upkeep efficiency can erase

    # --- life ------------------------------------------------------------
    base_lifespan: float = 120.0  # seconds at lifespan trait 0
    lifespan_range: float = 480.0  # extra seconds at lifespan trait 1

    # --- food -------------------------------------------------------------
    food_spawn_rate: float = 2.0  # food items per second
    max_food: int = 300  # food cap (the world is finite)
    food_energy: float = 30.0  # energy per food item
    initial_food_fraction: float = 0.6  # food present at t=0 (world starts alive)

    # --- senses ------------------------------------------------------------
    vision_base: float = 30.0  # sensing range in px at vision trait 0
    vision_range: float = 120.0  # extra range at vision trait 1
    sense_interval: float = 0.25  # seconds between re-senses
    hungry_level: float = 0.80  # fraction of max energy below which food is sought
    steer_rate: float = 6.0  # max turn toward target (rad/s), agility drops with size

    # --- reproduction -----------------------------------------------------
    mate_radius: float = 30.0  # partners must be within this distance
    mate_energy_gate: float = 50.0  # energy required to mate
    mate_cost: float = 18.0  # energy each parent spends
    baby_energy: float = 30.0  # energy a newborn starts with
    readiness_base: float = 0.10  # readiness gained/s at fertility 0
    readiness_fertility: float = 0.45  # extra gained/s at fertility 1
    # Aggressive organisms breed slower — a direct reproductive edge for
    # prey that keeps the population majority herbivore even under raids.
    repro_aggression_penalty: float = 0.8
    max_population: int = 300  # no births above this (safety valve)
    mutation_rate: float = 0.05  # per-trait mutation probability (slider-driven)
    # --- immigration -----------------------------------------------------
    # Safety net: a stream of fresh random immigrants keeps the lab
    # population from emptying out entirely. Now that reproduction is
    # live it rarely fires, but it guards against total extinction.
    min_population: int = 40
    migration_rate: float = 1.0  # immigrants per second while below floor

    # --- predation -----------------------------------------------------
    # Predation is continuous, driven by the aggression trait on a
    # 0..1 spectrum. Every hungry organism hunts weaker neighbours with
    # probability = aggression, and forages plant food with probability
    # (1 - aggression). Aggression also adds an upkeep surcharge, so a
    # truly carnivorous lifestyle has to pay for itself. Because the
    # benefit scales smoothly with the trait, aggressive predators can
    # evolve from a clean herbivore lineage step by step in mutations.
    predation_drain: float = 2.5  # steep upkeep: hunting must pay for itself
    prey_energy_gain: float = 22.0  # energy a predator gains per catch
    capture_bonus: float = 6.0  # px added to reach beyond both radii
    hunt_interval: float = 0.15  # seconds between prey re-scans
    # Aggression must exceed a sensed organism's by at least this margin
    # for it to count as prey (and to trigger fleeing) — so similar
    # neighbours ignore each other instead of flinching constantly.
    hunt_margin: float = 0.1
    flee_strength: float = 2.6  # how hard a weak-minded organism turns away
    flee_speed_boost: float = 1.5  # sprint multiplier while fleeing
    flee_drain_cost: float = 1.2  # extra drain/s while sprinting
    # Predators must stock far more energy to breed, so predator numbers
    # lag prey availability (predator-prey cycling) instead of flooding.
    predator_mate_gate_mult: float = 2.0


class Ecosystem:
    """All simulation state. No rendering, no pygame, no UI.

    The only thing an ecosystem knows how to do is advance by `dt` seconds.
    The UI owns the clock and calls `update`.
    """

    def __init__(self, config: WorldConfig) -> None:
        self.config = config
        self.organisms: list[Organism] = []
        self.food: list[Food] = []
        self.time = 0.0  # simulation time in seconds
        self.deaths: dict[str, int] = {"starvation": 0, "age": 0, "eaten": 0}
        self.births = 0  # lifetime count of births
        # (t, avg_speed, avg_size, population) sampled once per sim second
        self.history: list[tuple[float, float, float, int]] = []
        self._history_acc = 0.0
        self.grid = SpatialGrid(config.width, config.height)
        self._next_id = 1
        self._migration_acc = 0.0
        self._food_acc = 0.0
        self._food_ids: set[int] = set()
        self.eaten = 0  # lifetime count of food items consumed
        # Seed the world with a fully prey population (aggression pinned to
        # zero) so predators are not present at t=0: they emerge later as
        # aggressive mutations spread. That is the arc you actually watch.
        for _ in range(config.organisms):
            self._spawn(initial_prey=True)
        # The world starts with food already on the plate, not empty.
        for _ in range(int(config.max_food * config.initial_food_fraction)):
            self._spawn_food()

    # --- population -----------------------------------------------------

    def _spawn(self, initial_prey: bool = False) -> None:
        c = self.config
        if initial_prey:
            # Pin aggression to zero so the founder stock is all prey.
            # Predators then arise only as aggressive mutations spread.
            genome = random_genome()
            genome.aggression = 0.0
        else:
            genome = random_genome()
        self.organisms.append(
            Organism(
                id=self._next_id,
                x=random.random() * c.width,
                y=random.random() * c.height,
                heading=random.random() * 2 * math.pi,
                genome=genome,
                energy=random.uniform(0.4, 1.0) * c.max_energy,
                age=0.0,
            )
        )
        self._next_id += 1

    def _kill(self, o: Organism, cause: str) -> None:
        """Flag an organism as dead; swept out at the end of the tick.

        Marking (rather than list.remove) keeps the per-organism update
        loop safe: a predator may eat a prey that is still ahead in the
        iteration, and the prey then skips its turn because it is dead.
        """
        if not o.dead:
            o.dead = True
            self.deaths[cause] = self.deaths.get(cause, 0) + 1

    # --- food -------------------------------------------------------------

    def _spawn_food(self) -> None:
        c = self.config
        f = Food(
            id=self._next_id,  # shares the id space with organisms — ids are unique
            x=random.random() * c.width,
            y=random.random() * c.height,
            energy=c.food_energy,
        )
        self._next_id += 1
        self.food.append(f)
        self._food_ids.add(f.id)

    def _eat_food(self, f: Food) -> None:
        self.food.remove(f)
        self._food_ids.discard(f.id)
        self.eaten += 1

    def _update_food(self, dt: float) -> None:
        c = self.config
        if len(self.food) >= c.max_food:
            self._food_acc = 0.0
            return
        self._food_acc += dt * c.food_spawn_rate
        while self._food_acc >= 1.0 and len(self.food) < c.max_food:
            self._food_acc -= 1.0
            self._spawn_food()

    # --- sensing -----------------------------------------------------------

    def _vision_range(self, o: Organism) -> float:
        c = self.config
        return c.vision_base + o.genome.vision * c.vision_range

    def _sense_food(self, o: Organism) -> None:
        """Point `o.target` at the nearest food within vision, or None.

        Toroidal: distances are computed across the wrapped world.
        """
        c = self.config
        range_px = self._vision_range(o)
        r2 = range_px * range_px
        half_w, half_h = c.width / 2, c.height / 2

        best = None
        best_d2 = r2
        for f in self.food:
            dx = f.x - o.x
            if dx > half_w:
                dx -= c.width
            elif dx < -half_w:
                dx += c.width
            if dx * dx > best_d2:
                continue  # early reject on x alone
            dy = f.y - o.y
            if dy > half_h:
                dy -= c.height
            elif dy < -half_h:
                dy += c.height
            d2 = dx * dx + dy * dy
            if d2 < best_d2:
                best_d2 = d2
                best = f
        o.target = best

    def _hunts(self, o: Organism, p: Organism) -> bool:
        """Whether `o` would treat `p` as prey: p must be meaningfully
        weaker (lower aggression) and alive."""
        return (
            not p.dead
            and p is not o
            and o.genome.aggression - p.genome.aggression >= self.config.hunt_margin
        )

    def _scan_prey(self, o: Organism) -> None:
        """Point `o.prey_target` at the nearest weaker neighbour in vision."""
        c = self.config
        range_px = self._vision_range(o)
        r2 = range_px * range_px
        half_w, half_h = c.width / 2, c.height / 2
        best = None
        best_d2 = r2
        for p in self.organisms:
            if not self._hunts(o, p):
                continue
            dx = p.x - o.x
            if dx > half_w:
                dx -= c.width
            elif dx < -half_w:
                dx += c.width
            if dx * dx > best_d2:
                continue
            dy = p.y - o.y
            if dy > half_h:
                dy -= c.height
            elif dy < -half_h:
                dy += c.height
            d2 = dx * dx + dy * dy
            if d2 < best_d2:
                best_d2 = d2
                best = p
        o.prey_target = best

    def _scan_danger(self, o: Organism) -> None:
        """Point `o.danger` at the nearest meaningfully-stronger neighbour
        (a threat) in vision, or None."""
        c = self.config
        range_px = self._vision_range(o)
        r2 = range_px * range_px
        half_w, half_h = c.width / 2, c.height / 2
        best = None
        best_d2 = r2
        for p in self.organisms:
            if (
                p.dead
                or p is o
                or p.genome.aggression - o.genome.aggression < c.hunt_margin
            ):
                continue
            dx = p.x - o.x
            if dx > half_w:
                dx -= c.width
            elif dx < -half_w:
                dx += c.width
            if dx * dx > best_d2:
                continue
            dy = p.y - o.y
            if dy > half_h:
                dy -= c.height
            elif dy < -half_h:
                dy += c.height
            d2 = dx * dx + dy * dy
            if d2 < best_d2:
                best_d2 = d2
                best = p
        o.danger = best

    def _flee(self, o: Organism, danger: Organism, dt: float) -> None:
        """Turn the heading away from `danger` (toroidal bearing).

        Prey with some aggression stand their ground a little: the
        turning response is scaled by (1 - aggression), so nearly-pure
        prey run hard while borderline predators barely flinch.
        """
        c = self.config
        dx = o.x - danger.x
        if dx > c.width / 2:
            dx -= c.width
        elif dx < -c.width / 2:
            dx += c.width
        dy = o.y - danger.y
        if dy > c.height / 2:
            dy -= c.height
        elif dy < -c.height / 2:
            dy += c.height
        desired = math.atan2(dy, dx)  # bearing toward the danger
        away = desired + math.pi
        diff = math.atan2(math.sin(away - o.heading), math.cos(away - o.heading))
        turn = c.flee_strength * (1.0 - 0.5 * o.genome.size) * (1.0 - 0.7 * o.genome.aggression)
        o.heading += max(-turn * dt, min(turn * dt, diff))

    def _turn(self, o: Organism, dt: float) -> None:
        """Decide one organism's movement for this tick (continuous roles).

        Highest priority is fleeing a real threat — an organism with
        meaningfully more aggression nearby. Otherwise, when hungry, the
        aggression trait draws a line between hunting (chase weaker
        neighbours) and foraging (chase plant food): a soft commit per
        hunger span, so a creature doesn't flap between roles every tick.
        A well-fed organism just wanders, which is what lets prey breed
        between raids.
        """
        c = self.config

        # Fleeing outranks everything.
        if o.danger is not None and not o.danger.dead:
            o.fleeing = True
            self._flee(o, o.danger, dt)
            return

        hungry = o.energy < c.hungry_level * c.max_energy
        if not hungry:
            o.heading += (random.random() - 0.5) * 2 * c.wander_turn_rate * dt
            return

        # Choose a role once per hunger span, gated by the aggression trait.
        # `on_hunt` persists until the quarry dies or is caught. Do NOT
        # bump last_sense here — that throttle belongs to the food scan
        # alone, otherwise a would-be forager never re-senses food.
        if o.prey_target is None or o.prey_target.dead or self.time - o.last_hunt >= c.hunt_interval:
            o.on_hunt = random.random() < o.genome.aggression

        if o.on_hunt:
            if o.prey_target is None or o.prey_target.dead:
                self._scan_prey(o)
            if o.prey_target is not None and not o.prey_target.dead:
                # Reuse the steer; `_steer_toward` reads o.target, so point
                # it at the quarry for the turn then restore.
                saved = o.target
                o.target = o.prey_target  # type: ignore[assignment]
                self._steer_toward(o, dt)
                o.target = saved
            else:
                o.heading += (random.random() - 0.5) * 2 * c.wander_turn_rate * dt
            return

        # Foraging for plant food.
        if self.time - o.last_sense >= c.sense_interval:
            if o.target is None or o.target.id not in self._food_ids:
                self._sense_food(o)
                o.last_sense = self.time
        if o.target is not None:
            self._steer_toward(o, dt)
        else:
            o.heading += (random.random() - 0.5) * 2 * c.wander_turn_rate * dt

    def _try_catch(self, o: Organism) -> None:
        """Catch the hunted prey: kill it and gain energy.

        Catching is a hard speed gate: a predator only catches prey that
        it can actually outrun while the prey sprints away. A faster prey
        is uncatchable and gets away, so the arms race is real — prey
        evolve speed to escape, predators evolve speed to chase — and a
        lone carnivore cannot clear the whole plate, because the faster
        prey simply outlive it.
        """
        c = self.config
        prey = o.prey_target
        if prey is None or prey.dead:
            return
        dx = prey.x - o.x
        if dx > c.width / 2:
            dx -= c.width
        elif dx < -c.width / 2:
            dx += c.width
        dy = prey.y - o.y
        if dy > c.height / 2:
            dy -= c.height
        elif dy < -c.height / 2:
            dy += c.height
        reach = body_radius_px(o.genome.size) + body_radius_px(prey.genome.size) + c.capture_bonus
        if dx * dx + dy * dy > reach * reach:
            return

        pred_speed = move_speed_px(o.genome)
        prey_sprint = move_speed_px(prey.genome) * c.flee_speed_boost
        if pred_speed < prey_sprint:
            return  # outrun: the prey escapes
        o.energy = min(c.max_energy, o.energy + c.prey_energy_gain)
        self._kill(prey, "eaten")
        o.prey_target = None

    def _try_eat(self, o: Organism) -> None:
        """Plant food: gain the food's energy when touching it."""
        c = self.config
        f = o.target
        if f is None or f.id not in self._food_ids:
            return
        dx = f.x - o.x
        if dx > c.width / 2:
            dx -= c.width
        elif dx < -c.width / 2:
            dx += c.width
        dy = f.y - o.y
        if dy > c.height / 2:
            dy -= c.height
        elif dy < -c.height / 2:
            dy += c.height
        reach = body_radius_px(o.genome.size) + 3
        if dx * dx + dy * dy <= reach * reach:
            o.energy = min(c.max_energy, o.energy + f.energy)
            self._eat_food(f)
            o.target = None

    # --- behaviour ------------------------------------------------------

    def update(self, dt: float) -> None:
        """Advance the simulation by `dt` seconds."""
        self.time += dt
        c = self.config

        for o in list(self.organisms):
            if o.dead:
                continue  # a predator already ate it earlier this tick

            o.age += dt
            repro = (c.readiness_base + c.readiness_fertility * o.genome.fertility)
            repro *= 1.0 - c.repro_aggression_penalty * o.genome.aggression
            o.readiness += repro * dt

            # Re-sense danger on the sense cadence, then pick behaviour.
            if o.danger is None or o.danger.dead:
                if self.time - o.last_sense >= c.sense_interval:
                    self._scan_danger(o)
            self._turn(o, dt)

            speed = move_speed_px(o.genome)
            if o.fleeing:
                speed *= c.flee_speed_boost
            o.x += math.cos(o.heading) * speed * dt
            o.y += math.sin(o.heading) * speed * dt

            # Toroidal world: wrap around the edges instead of hitting walls.
            self._wrap(o)

            drain = self._drain(o.genome)
            if o.fleeing:
                drain += c.flee_drain_cost
            o.energy = max(0.0, o.energy - drain * dt)
            o.fleeing = False  # reset for the next tick
            if o.energy <= 0.0:
                self._kill(o, "starvation")
                continue
            if o.age >= self._max_age(o.genome):
                self._kill(o, "age")
                continue

            if o.on_hunt and o.prey_target is not None:
                # Closing in: catch the quarry that comes within reach.
                self._try_catch(o)
            else:
                # Eat plant food: touching the targeted food.
                self._try_eat(o)

        # Sweep out everything that died this tick (see `_kill` docstring).
        self.organisms = [o for o in self.organisms if not o.dead]

        self._update_food(dt)
        self.grid.rebuild(self.organisms)
        self._mate()
        self._migrate(dt)

        # Sample the stats graph once per simulated second.
        self._history_acc += dt
        if self._history_acc >= 1.0:
            self._history_acc -= 1.0
            self.history.append(
                (
                    self.time,
                    self.trait_average("speed"),
                    self.trait_average("size"),
                    len(self.organisms),
                )
            )
            if len(self.history) > 300:
                del self.history[0]

    def _steer_toward(self, o: Organism, dt: float) -> None:
        """Turn the heading toward the target at a max rate (toroidal).

        Agility drops with size: big creatures are sluggish.
        """
        c = self.config
        t = o.target
        dx = t.x - o.x
        if dx > c.width / 2:
            dx -= c.width
        elif dx < -c.width / 2:
            dx += c.width
        dy = t.y - o.y
        if dy > c.height / 2:
            dy -= c.height
        elif dy < -c.height / 2:
            dy += c.height

        desired = math.atan2(dy, dx)
        diff = math.atan2(math.sin(desired - o.heading), math.cos(desired - o.heading))
        turn = c.steer_rate * (1.0 - 0.5 * o.genome.size)
        o.heading += max(-turn * dt, min(turn * dt, diff))

    # --- reproduction -----------------------------------------------------

    def _mate(self) -> None:
        """Local mating: a ready, energetic organism pairs with a nearby
        ready partner; the two pay the cost and produce one mutated
        crossover baby at their (toroidal) midpoint.
        """
        c = self.config
        for o in list(self.organisms):
            if len(self.organisms) >= c.max_population:
                break
            # Carnivorous organisms must stock far more energy to breed, so
            # predator numbers lag prey availability instead of flooding.
            carnivory = o.genome.aggression
            gate = c.mate_energy_gate * (1.0 + (c.predator_mate_gate_mult - 1.0) * carnivory)
            if o.readiness < 1.0 or o.energy < gate:
                continue
            partner = self._find_partner(o)
            if partner is None:
                continue

            o.energy -= c.mate_cost
            partner.energy -= c.mate_cost
            o.readiness = 0.0
            partner.readiness = 0.0

            # Toroidal midpoint, so a pair straddling an edge still
            # produces a baby between them.
            dx = partner.x - o.x
            if dx > c.width / 2:
                dx -= c.width
            elif dx < -c.width / 2:
                dx += c.width
            dy = partner.y - o.y
            if dy > c.height / 2:
                dy -= c.height
            elif dy < -c.height / 2:
                dy += c.height

            genome = mutate(crossover(o.genome, partner.genome), c.mutation_rate)
            baby = Organism(
                id=self._next_id,
                x=o.x + dx / 2,
                y=o.y + dy / 2,
                heading=random.random() * 2 * math.pi,
                genome=genome,
                energy=c.baby_energy,
                age=0.0,
                generation=max(o.generation, partner.generation) + 1,
            )
            self._next_id += 1
            self._wrap(baby)
            self.organisms.append(baby)
            self.births += 1

    def _find_partner(self, o: Organism) -> Organism | None:
        """First ready, energetic neighbor within the mating radius."""
        c = self.config
        for p in self.grid.within(o.x, o.y, c.mate_radius):
            if p is not o and p.readiness >= 1.0 and p.energy >= c.mate_energy_gate:
                return p
        return None

    # --- trait costs -----------------------------------------------------

    def _drain(self, g: Genome) -> float:
        """Energy per second: metabolism × movement/body upkeep − efficiency.

        Predators pay an aggression surcharge so hunting has to actually
        pay for itself — an aggression-heavy genome that never catches
        prey starves, which is the whole selection pressure.
        """
        c = self.config
        metabolism = c.base_metabolism + g.metabolism * c.metabolism_range
        upkeep = 1.0 + g.speed * c.speed_cost + g.size * c.size_cost
        saving = 1.0 - g.efficiency * c.efficiency_saving
        aggression = 1.0 + g.aggression * c.predation_drain
        return metabolism * upkeep * saving * aggression

    def _max_age(self, g: Genome) -> float:
        c = self.config
        return c.base_lifespan + g.lifespan * c.lifespan_range

    # --- observations ----------------------------------------------------

    def trait_average(self, trait: str) -> float:
        """Average of a genome trait across the population, or 0 if empty."""
        pop = self.organisms
        if not pop:
            return 0.0
        return sum(getattr(o.genome, trait) for o in pop) / len(pop)

    # --- helpers ----------------------------------------------------------

    def _migrate(self, dt: float) -> None:
        c = self.config
        if len(self.organisms) >= c.min_population:
            self._migration_acc = 0.0
            return
        self._migration_acc += dt * c.migration_rate
        while self._migration_acc >= 1.0 and len(self.organisms) < c.min_population:
            self._migration_acc -= 1.0
            self._spawn()

    def _wrap(self, o: Organism) -> None:
        c = self.config
        if o.x < 0:
            o.x += c.width
        elif o.x >= c.width:
            o.x -= c.width
        if o.y < 0:
            o.y += c.height
        elif o.y >= c.height:
            o.y -= c.height


# ===== ui/widgets.py =====
"""Tiny hand-drawn UI widgets (pygame draws its own control elements).

These are the building blocks for every panel later: controls sidebar,
organism inspector, experiment picker. Each widget owns its rect, knows
how to draw itself, and returns True from `handle` when it was activated.
"""

import pygame



class Label:
    def __init__(
        self,
        pos: tuple[int, int],
        text: str,
        font: pygame.font.Font,
        color: tuple[int, int, int] = TEXT_DIM,
    ) -> None:
        self.pos = pos  # midleft anchor
        self.font = font
        self.color = color
        self.text = text
        self.surface = font.render(text, True, color)

    def set_text(self, text: str) -> None:
        if text != self.text:
            self.text = text
            self.surface = self.font.render(text, True, self.color)

    def draw(self, surface: pygame.Surface) -> None:
        surface.blit(self.surface, self.surface.get_rect(midleft=self.pos))


class Button:
    def __init__(
        self,
        rect: pygame.Rect | tuple[int, int, int, int],
        label: str,
        font: pygame.font.Font,
    ) -> None:
        self.rect = pygame.Rect(rect)
        self.label = label
        self.font = font
        self._pressed = False

    def handle(self, event: pygame.event.Event) -> bool:
        """Process one event; True when the button was clicked."""
        if event.type == pygame.MOUSEBUTTONDOWN and event.button == 1:
            self._pressed = self.rect.collidepoint(event.pos)
        elif event.type == pygame.MOUSEBUTTONUP and event.button == 1:
            clicked = self._pressed and self.rect.collidepoint(event.pos)
            self._pressed = False
            return clicked
        return False

    def draw(self, surface: pygame.Surface) -> None:
        pygame.draw.rect(surface, PANEL, self.rect, border_radius=6)
        pygame.draw.rect(surface, ACCENT, self.rect, width=1, border_radius=6)
        text = self.font.render(self.label, True, TEXT)
        surface.blit(text, text.get_rect(center=self.rect.center))


class Slider:
    """Horizontal slider; value snapped to `step` increments."""

    def __init__(
        self,
        rect: pygame.Rect | tuple[int, int, int, int],
        font: pygame.font.Font,
        min_value: float,
        max_value: float,
        value: float,
        step: float = 0.25,
    ) -> None:
        self.rect = pygame.Rect(rect)
        self.font = font
        self.min = min_value
        self.max = max_value
        self.step = step
        self._value = value
        self._drag = False

    @property
    def value(self) -> float:
        return self._value

    def _set_from_x(self, x: int) -> None:
        t = max(0.0, min(1.0, (x - self.rect.left) / self.rect.width))
        raw = self.min + t * (self.max - self.min)
        self._value = round(raw / self.step) * self.step

    def _knob_x(self) -> int:
        t = (self._value - self.min) / (self.max - self.min)
        return self.rect.left + round(t * self.rect.width)

    def handle(self, event: pygame.event.Event) -> None:
        if event.type == pygame.MOUSEBUTTONDOWN and event.button == 1:
            self._drag = self.rect.collidepoint(event.pos)
            if self._drag:
                self._set_from_x(event.pos[0])
        elif event.type == pygame.MOUSEMOTION and self._drag:
            self._set_from_x(event.pos[0])
        elif event.type == pygame.MOUSEBUTTONUP and event.button == 1:
            self._drag = False

    def draw(self, surface: pygame.Surface) -> None:
        y = self.rect.centery
        pygame.draw.line(surface, PANEL_BORDER, (self.rect.left, y), (self.rect.right, y), 3)
        knob = self._knob_x()
        if knob > self.rect.left:
            pygame.draw.line(surface, ACCENT, (self.rect.left, y), (knob, y), 3)
        pygame.draw.circle(surface, ACCENT, (knob, y), 6)
        pygame.draw.circle(surface, BG, (knob, y), 2)


# ===== rendering/renderer.py =====
"""Draws the ecosystem onto a pygame surface.

The renderer is a dumb view: it reads simulation state and paints it.
The static background (fill + grid) is pre-rendered once and blitted
every frame, so the per-frame cost is one blit plus the organisms.

Organisms are drawn from a pre-rendered "orb atlas": antialiased radial
sprites baked at init for every (species, radius, energy-brightness)
combination, so the per-frame cost is a single blit per organism with
smooth soft-edged cells. Traits are still visible on the plate:
    size       -> body radius
    energy     -> body brightness (dim = starving)
    speed      -> heading tick length
    aggression -> species colour (prey = green, predator = red)
"""

import math

import pygame


GRID_SPACING = 64
MAX_TICK = 14  # px at max speed
RADIUS_STEPS = list(range(2, 9))  # rounded body radii (2..8 px)
ENERGY_LEVELS = 8  # brightness buckets for the atlas
AGGRESSION_BUCKETS = 8  # colour buckets for the aggression spectrum
GLOW = 2  # px of soft halo around each orb

# Colors at zero energy (dim) for each species.
_STARVED_PREY = (30, 90, 62)
_STARVED_PRED = (94, 38, 38)


def _lerp(a: tuple[int, int, int], b: tuple[int, int, int], t: float) -> tuple[int, int, int]:
    return tuple(round(av + (bv - av) * t) for av, bv in zip(a, b))


def _orb_color(species: str, level: int) -> tuple[int, int, int]:
    """Body color for an atlas cell: brightness rises with the energy level."""
    t = level / (ENERGY_LEVELS - 1) if ENERGY_LEVELS > 1 else 1.0
    if species == "pred":
        return _lerp(_STARVED_PRED, PREDATOR, t)
    return _lerp(_STARVED_PREY, ACCENT, t)


def _aggression_color(aggression: float, level: int) -> tuple[int, int, int]:
    """Body color across the aggression spectrum: herbivore green at low
    aggression, shifting through amber to carnivore red at high aggression.
    The energy level still controls brightness (dim = starving).
    """
    t = min(1.0, max(0.0, aggression))
    green = _orb_color("prey", level)
    red = _orb_color("pred", level)
    warm = _lerp(green, red, 0.45)  # amber midpoint
    if t < 0.5:
        return _lerp(green, warm, t * 2.0)
    return _lerp(warm, red, (t - 0.5) * 2.0)


def _make_orb(color: tuple[int, int, int], radius: int, glow: int = GLOW) -> pygame.Surface:
    """A soft-edged radial orb: full-colour body fading into the halo."""
    side = (radius + glow) * 2 + 2
    surf = pygame.Surface((side, side), pygame.SRCALPHA)
    c = side // 2
    # Halo: a thin fading ring outside the body.
    for rr in range(radius + glow, radius, -1):
        a = int(255 * (radius + glow - rr + 1) / (glow + 1))
        pygame.draw.circle(surf, (*color, a), (c, c), rr)
    # Body in full colour.
    pygame.draw.circle(surf, (*color, 255), (c, c), radius)
    # Brighter inner core for depth.
    core = _lerp(color, (255, 255, 255), 0.35)
    pygame.draw.circle(surf, (*core, 220), (c, c), max(1, int(radius * 0.7)))
    inner = _lerp(color, (255, 255, 255), 0.65)
    pygame.draw.circle(surf, (*inner, 160), (c, c), max(1, int(radius * 0.4)))
    return surf


class Renderer:
    def __init__(self, surface: pygame.Surface) -> None:
        self.surface = surface
        self.font = pygame.font.SysFont("dejavusansmono,consolas,monospace", 10)
        w, h = surface.get_size()
        self.background = self._build_background(w, h)
        self.atlas: dict[tuple[int, int, int], pygame.Surface] = {
            (agg, radius, lvl): _make_orb(
                _aggression_color(agg / (AGGRESSION_BUCKETS - 1), lvl), radius
            )
            for agg in range(AGGRESSION_BUCKETS)
            for radius in RADIUS_STEPS
            for lvl in range(ENERGY_LEVELS)
        }
        self.food_sprite = _make_orb(FOOD, 3, glow=1)

    def _build_background(self, w: int, h: int) -> pygame.Surface:
        bg = pygame.Surface((w, h))
        bg.fill(BG)

        grid = pygame.Surface((w, h), pygame.SRCALPHA)
        for x in range(0, w + 1, GRID_SPACING):
            pygame.draw.line(grid, (*TEXT_DIM, GRID_ALPHA), (x, 0), (x, h))
        for y in range(0, h + 1, GRID_SPACING):
            pygame.draw.line(grid, (*TEXT_DIM, GRID_ALPHA), (0, y), (w, y))
        bg.blit(grid, (0, 0))
        return bg

    def render(self, world: Ecosystem) -> None:
        self.surface.blit(self.background, (0, 0))

        # Food under the organisms (a soft amber orb, consistent with the cells)
        fs = self.food_sprite.get_width() // 2
        for f in world.food:
            self.surface.blit(self.food_sprite, (int(f.x) - fs, int(f.y) - fs))

        for o in world.organisms:
            radius = body_radius_px(o.genome.size)
            tick = 4 + o.genome.speed * MAX_TICK  # 4..18 px
            aggression = o.genome.aggression
            tick_color = _lerp(HEADING, HEADING_PRED, aggression)

            # heading tick: a short directional notch under the body
            pygame.draw.line(
                self.surface,
                tick_color,
                (o.x, o.y),
                (o.x + math.cos(o.heading) * tick,
                 o.y + math.sin(o.heading) * tick),
                1,
            )
            # body: pre-rendered orb (aggression + radius + energy brightness)
            lvl = min(
                ENERGY_LEVELS - 1,
                max(0, int(o.energy / world.config.max_energy * ENERGY_LEVELS)),
            )
            agg = min(
                AGGRESSION_BUCKETS - 1,
                max(0, int(aggression * AGGRESSION_BUCKETS)),
            )
            orb = self.atlas[(agg, round(radius), lvl)]
            self.surface.blit(orb, (int(o.x) - orb.get_width() // 2,
                                    int(o.y) - orb.get_height() // 2))

            # ready to mate: a thin ring around the body
            if o.readiness >= 1.0:
                ring = _lerp(ACCENT, PREDATOR, aggression)
                pygame.draw.circle(
                    self.surface,
                    ring,
                    (int(o.x), int(o.y)),
                    round(radius) + 2,
                    1,
                )

        self._draw_history(world)

    def _draw_history(self, world: Ecosystem) -> None:
        """Bottom-right sparklines: population (accent) and avg speed (dim)."""
        hist = world.history
        if len(hist) < 2:
            return
        w, h = self.surface.get_size()
        panel = pygame.Rect(w - 196, h - 80, 184, 68)
        pygame.draw.rect(self.surface, PANEL, panel, border_radius=6)
        pygame.draw.rect(self.surface, PANEL_BORDER, panel, width=1, border_radius=6)

        plot = panel.inflate(-12, -30)
        n = len(hist)
        pop_scale = float(world.config.max_population)

        def polyline(key: int, scale: float, color: tuple[int, int, int]) -> None:
            pts = []
            for i, sample in enumerate(hist):
                x = plot.left + (i / (n - 1)) * plot.width
                y = plot.bottom - min(1.0, sample[key] / scale) * plot.height
                pts.append((x, y))
            pygame.draw.lines(self.surface, color, False, pts, 1)

        polyline(3, pop_scale, ACCENT)  # population
        polyline(1, 1.0, TEXT_DIM)  # avg speed

        self.surface.blit(self.font.render("pop", True, ACCENT),
                          (panel.left + 6, panel.bottom - 13))
        self.surface.blit(self.font.render("avg spd", True, TEXT_DIM),
                          (panel.left + 40, panel.bottom - 13))


# ===== main.py =====
"""EvoLab — an artificial ecosystem simulator.

Run:  python main.py
Controls:  Space = pause/resume, mouse = pause button, speed and
mutation-rate sliders.
"""

import argparse
import asyncio
import sys

import pygame


# True under PyScript/Pyodide (WebAssembly) — the browser drives the
# frame timing, so the loop must yield with `await` instead of blocking.
IN_BROWSER = sys.platform == "emscripten"

WIDTH, HEIGHT = 1280, 800

# Fixed simulation step in seconds (60 Hz game-logic tick).
STEP = 1 / 60
# Max steps caught up per frame — prevents the "spiral of death"
# when the window is dragged/backgrounded at high speed.
MAX_STEPS_PER_FRAME = 32

def _load_font(names: str, size: int, bold: bool = False):
    """SysFont on desktop; falls back to pygame's bundled font where
    system fonts are unavailable (e.g. the Pyodide web build)."""
    try:
        f = pygame.font.SysFont(names, size, bold=bold)
        if f is not None:
            return f
    except Exception:
        pass
    return pygame.font.Font(None, size)


async def main() -> int:
    parser = argparse.ArgumentParser(description="EvoLab — artificial ecosystem simulator")
    parser.add_argument(
        "--frames", type=int, default=0,
        help="quit after N rendered frames (0 = run until closed)",
    )
    args = parser.parse_args()

    pygame.init()
    screen = pygame.display.set_mode((WIDTH, HEIGHT))
    font = _load_font("dejavusansmono,consolas,monospace", 14)
    logo_font = _load_font("dejavusans,verdana,sans-serif", 14, bold=True)
    clock = pygame.time.Clock()

    world = Ecosystem(
        WorldConfig(
            width=WIDTH, height=HEIGHT, organisms=80,
            wander_turn_rate=1.6,
        )
    )
    renderer = Renderer(screen)

    # --- header chrome -------------------------------------------------
    header = pygame.Rect(12, 12, WIDTH - 24, 46)
    cy = header.centery
    logo = Label((header.left + 16, cy), "EVOLAB", logo_font, ACCENT)
    population = Label((140, cy), "Population: 80", font)
    food = Label((272, cy), "Food: 0", font)
    generation = Label((362, cy), "Gen: 1", font)
    traits = Label((444, cy), "avg speed 50%  size 50%", font)
    pause_btn = Button((650, cy - 14, 100, 28), "Pause", font)
    mut_label = Label((764, cy), "mut", font, TEXT_DIM)
    mut_slider = Slider((798, cy - 8, 110, 16), font, 0.001, 0.20, 0.05, step=0.001)
    mut_value = Label((914, cy), "5.0%", font)
    speed_value = Label((966, cy), "1.0x", font)
    speed_slider = Slider((1006, cy - 8, 170, 16), font, 0.25, 20.0, 1.0)

    paused = False
    accumulator = 0.0
    frame = 0

    running = True
    while running:
        # dt in seconds, clamped so a long stall doesn't teleport the sim.
        # In the browser the page drives the frame: yield to the event loop
        # and measure elapsed time instead of blocking on the clock.
        if IN_BROWSER:
            await asyncio.sleep(1 / 60)
            dt = min(clock.tick(0) / 1000.0, 0.25)
        else:
            dt = min(clock.tick(60) / 1000.0, 0.25)

        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
            elif event.type == pygame.KEYDOWN and event.key == pygame.K_SPACE:
                paused = not paused
            if pause_btn.handle(event):
                paused = not paused
            speed_slider.handle(event)
            mut_slider.handle(event)

        world.config.mutation_rate = mut_slider.value

        if not paused:
            # fixed timestep with accumulator: speed scales the number of
            # steps per real second, never the size of a step
            accumulator += dt * speed_slider.value
            steps = 0
            while accumulator >= STEP and steps < MAX_STEPS_PER_FRAME:
                world.update(STEP)
                accumulator -= STEP
                steps += 1
            if steps == MAX_STEPS_PER_FRAME:
                accumulator = 0.0  # drop the backlog

        renderer.render(world)

        # --- chrome -----------------------------------------------------
        pygame.draw.rect(screen, PANEL, header, border_radius=8)
        pygame.draw.rect(screen, PANEL_BORDER, header, width=1, border_radius=8)
        population.set_text(f"Population: {len(world.organisms)}")
        food.set_text(f"Food: {len(world.food)}")
        generation.set_text(f"Gen: {max((o.generation for o in world.organisms), default=0)}")
        speed_value.set_text(f"{speed_slider.value:.1f}x")
        mut_value.set_text(f"{mut_slider.value * 100:.1f}%")
        traits.set_text(
            f"avg speed {round(world.trait_average('speed') * 100)}%"
            f"  size {round(world.trait_average('size') * 100)}%"
        )
        logo.draw(screen)
        population.draw(screen)
        food.draw(screen)
        generation.draw(screen)
        traits.draw(screen)
        mut_label.draw(screen)
        mut_slider.draw(screen)
        mut_value.draw(screen)
        speed_value.draw(screen)
        speed_slider.draw(screen)
        pause_btn.draw(screen)

        pygame.display.flip()
        frame += 1
        if args.frames and frame >= args.frames:
            running = False

    pygame.quit()
    return 0


# --- web entry ------------------------------------------------------------
# PyScript executes this file as a script (in an async context), so the
# game is started explicitly: as a task if a loop is already running, or
# via asyncio.run otherwise.
try:
    asyncio.get_running_loop()
    asyncio.create_task(main())
except RuntimeError:
    asyncio.run(main())

try:  # cosmetic: hide the loading line once the game is up
    from pyscript import window as _win

    _status = _win.document.getElementById("status")
    if _status:
        _status.style.display = "none"
except Exception:
    pass
