"""EvoLab web build — generated by web/build.py, do not edit by hand.

Single-file concatenation of the project modules so PyScript's
<script type="py-game"> can execute one entry file. Re-run
`python web/build.py` after changing any source module.
"""


# ===== ui/theme.py =====
"""Shared color palette — the "scientific research lab" dark theme."""

BG = (11, 15, 20)          # window background
PANEL = (16, 22, 29)       # chrome panels
PANEL_BORDER = (29, 39, 51)
TEXT = (203, 213, 225)
TEXT_DIM = (100, 116, 139)
ACCENT = (52, 211, 153)    # organism green / interactive accent
FOOD = (212, 175, 55)       # food item — amber, distinct from organism green
HEADING = (32, 140, 102)   # heading tick, dimmer than the dot
GRID_ALPHA = 14            # lab-plate grid line alpha (0-255)


# ===== simulation/genome.py =====
"""Heritable traits: the genome and its mapping to visible phenotypes.

Every trait is a float in [0, 1]. Higher is not always better — each
trait carries a tradeoff enforced in `energy_drain_per_s` and friends.

Wired into the simulation right now: speed, size, metabolism, lifespan,
efficiency, vision (sensing), fertility (reproduction). Still dormant:
aggression (predation).
"""

import random
from dataclasses import dataclass

TRAIT_NAMES = (
    "speed",
    "size",
    "vision",
    "metabolism",
    "fertility",
    "lifespan",
    "aggression",
    "efficiency",
)


@dataclass(slots=True)
class Genome:
    speed: float  # faster movement, higher movement upkeep
    size: float  # bigger body, higher upkeep, bigger target
    vision: float  # sensing range (food/predators) — dormant
    metabolism: float  # base energy burn rate
    fertility: float  # reproduction readiness — dormant
    lifespan: float  # max age in seconds
    aggression: float  # predator behavior — dormant
    efficiency: float  # lowers every energy cost


def random_genome() -> Genome:
    return Genome(*(random.random() for _ in TRAIT_NAMES))


# --- genetics --------------------------------------------------------

def crossover(a: Genome, b: Genome) -> Genome:
    """Uniform crossover: each trait is copied from a random parent."""
    return Genome(
        **{n: random.choice((getattr(a, n), getattr(b, n))) for n in TRAIT_NAMES}
    )


def mutate(g: Genome, rate: float) -> Genome:
    """Per-trait point mutation: with probability `rate`, nudge the trait.

    The nudge is a Gaussian step clamped to [0, 1]. `rate` is the
    probability per trait (the user-facing mutation slider).
    """
    if rate <= 0.0:
        return g
    vals = {}
    for n in TRAIT_NAMES:
        v = getattr(g, n)
        if random.random() < rate:
            v = max(0.0, min(1.0, v + random.gauss(0.0, 0.15)))
        vals[n] = v
    return Genome(**vals)


# --- phenotype mapping (pure geometry) --------------------------------

def body_radius_px(size: float) -> float:
    return 2.0 + size * 6.0  # 2..8 px


def move_speed_px(genome: Genome) -> float:
    return 10.0 + genome.speed * 60.0  # 10..70 px/s


# ===== simulation/food.py =====
"""Food — the resource organisms compete for."""

from dataclasses import dataclass


@dataclass(slots=True)
class Food:
    id: int
    x: float
    y: float
    energy: float


# ===== simulation/types.py =====
from dataclasses import dataclass



@dataclass(slots=True)
class Organism:
    """A living organism with a heritable genome.

    Energy drains every tick (metabolism + movement + body upkeep);
    hitting zero means starvation death. Ageing past the genome's
    lifespan means natural death.
    """

    id: int
    x: float
    y: float
    heading: float  # movement direction in radians
    genome: Genome
    energy: float
    age: float
    generation: int = 1  # genealogical generation (initial stock is 1)
    readiness: float = 0.0  # accumulates to 1.0, gated by fertility
    target: Food | None = None  # food currently being chased
    last_sense: float = 0.0  # sim time of the last food scan


# ===== simulation/spatial.py =====
"""Spatial hash grid: fast neighbor queries on the toroidal world.

Rebuilt once per tick (cheap: one dict insert per item). Queries scan
only the cells a circle overlaps, so cost is independent of population
size for small radii — this is what makes local mating (and later,
predation) affordable at large populations.
"""

import math


class SpatialGrid:
    def __init__(self, width: int, height: int, cell: int = 64) -> None:
        self.width = width
        self.height = height
        self.cell = cell
        self.cols = max(1, math.ceil(width / cell))
        self.rows = max(1, math.ceil(height / cell))
        self.cells: dict[tuple[int, int], list] = {}

    def rebuild(self, items: list) -> None:
        self.cells.clear()
        for it in items:
            key = (int(it.x) // self.cell, int(it.y) // self.cell)
            bucket = self.cells.get(key)
            if bucket is None:
                self.cells[key] = [it]
            else:
                bucket.append(it)

    def within(self, x: float, y: float, radius: float) -> list:
        """Items within `radius` of (x, y), toroidal-aware."""
        c = self.cell
        half_w, half_h = self.width / 2, self.height / 2
        r2 = radius * radius
        x0 = int((x - radius) // c)
        x1 = int((x + radius) // c)
        y0 = int((y - radius) // c)
        y1 = int((y + radius) // c)

        out = []
        for cx in range(x0, x1 + 1):
            for cy in range(y0, y1 + 1):
                bucket = self.cells.get((cx % self.cols, cy % self.rows))
                if not bucket:
                    continue
                for it in bucket:
                    dx = it.x - x
                    if dx > half_w:
                        dx -= self.width
                    elif dx < -half_w:
                        dx += self.width
                    if dx * dx > r2:
                        continue
                    dy = it.y - y
                    if dy > half_h:
                        dy -= self.height
                    elif dy < -half_h:
                        dy += self.height
                    if dx * dx + dy * dy <= r2:
                        out.append(it)
        return out


# ===== simulation/ecosystem.py =====
"""EvoLab — artificial ecosystem simulator."""

import math
import random
from dataclasses import dataclass



@dataclass
class WorldConfig:
    width: int
    height: int
    organisms: int  # starting organism count
    wander_turn_rate: float  # how eagerly a creature changes direction (rad/s)

    # --- energy ---------------------------------------------------------
    max_energy: float = 100.0
    # drain/s = (base + range*metabolism) * (1 + speed_cost*speed + size_cost*size)
    #          * (1 - efficiency_saving*efficiency)
    base_metabolism: float = 0.30  # energy/s at minimal traits
    metabolism_range: float = 0.55  # extra burn from the metabolism trait
    speed_cost: float = 0.6  # upkeep multiplier weight for speed trait
    size_cost: float = 0.8  # upkeep multiplier weight for size trait
    efficiency_saving: float = 0.5  # fraction of upkeep efficiency can erase

    # --- life ------------------------------------------------------------
    base_lifespan: float = 120.0  # seconds at lifespan trait 0
    lifespan_range: float = 480.0  # extra seconds at lifespan trait 1

    # --- food -------------------------------------------------------------
    food_spawn_rate: float = 2.0  # food items per second
    max_food: int = 250  # food cap (the world is finite)
    food_energy: float = 30.0  # energy per food item
    initial_food_fraction: float = 0.6  # food present at t=0 (world starts alive)

    # --- senses ------------------------------------------------------------
    vision_base: float = 30.0  # sensing range in px at vision trait 0
    vision_range: float = 120.0  # extra range at vision trait 1
    sense_interval: float = 0.25  # seconds between re-senses
    hungry_level: float = 0.80  # fraction of max energy below which food is sought
    steer_rate: float = 6.0  # max turn toward target (rad/s), agility drops with size

    # --- reproduction -----------------------------------------------------
    mate_radius: float = 30.0  # partners must be within this distance
    mate_energy_gate: float = 50.0  # energy required to mate
    mate_cost: float = 25.0  # energy each parent spends
    baby_energy: float = 30.0  # energy a newborn starts with
    readiness_base: float = 0.05  # readiness gained/s at fertility 0
    readiness_fertility: float = 0.45  # extra gained/s at fertility 1
    max_population: int = 300  # no births above this (safety valve)
    mutation_rate: float = 0.05  # per-trait mutation probability (slider-driven)
    # --- immigration -----------------------------------------------------
    # Safety net: a stream of fresh random immigrants keeps the lab
    # population from emptying out entirely. Now that reproduction is
    # live it rarely fires, but it guards against total extinction.
    min_population: int = 40
    migration_rate: float = 1.0  # immigrants per second while below floor


class Ecosystem:
    """All simulation state. No rendering, no pygame, no UI.

    The only thing an ecosystem knows how to do is advance by `dt` seconds.
    The UI owns the clock and calls `update`.
    """

    def __init__(self, config: WorldConfig) -> None:
        self.config = config
        self.organisms: list[Organism] = []
        self.food: list[Food] = []
        self.time = 0.0  # simulation time in seconds
        self.deaths: dict[str, int] = {"starvation": 0, "age": 0}
        self.births = 0  # lifetime count of births
        # (t, avg_speed, avg_size, population) sampled once per sim second
        self.history: list[tuple[float, float, float, int]] = []
        self._history_acc = 0.0
        self.grid = SpatialGrid(config.width, config.height)
        self._next_id = 1
        self._migration_acc = 0.0
        self._food_acc = 0.0
        self._food_ids: set[int] = set()
        self.eaten = 0  # lifetime count of food items consumed
        for _ in range(config.organisms):
            self._spawn()
        # The world starts with food already on the plate, not empty.
        for _ in range(int(config.max_food * config.initial_food_fraction)):
            self._spawn_food()

    # --- population -----------------------------------------------------

    def _spawn(self) -> None:
        c = self.config
        self.organisms.append(
            Organism(
                id=self._next_id,
                x=random.random() * c.width,
                y=random.random() * c.height,
                heading=random.random() * 2 * math.pi,
                genome=random_genome(),
                energy=random.uniform(0.4, 1.0) * c.max_energy,
                age=0.0,
            )
        )
        self._next_id += 1

    def _kill(self, o: Organism, cause: str) -> None:
        self.organisms.remove(o)
        self.deaths[cause] = self.deaths.get(cause, 0) + 1

    # --- food -------------------------------------------------------------

    def _spawn_food(self) -> None:
        c = self.config
        f = Food(
            id=self._next_id,  # shares the id space with organisms — ids are unique
            x=random.random() * c.width,
            y=random.random() * c.height,
            energy=c.food_energy,
        )
        self._next_id += 1
        self.food.append(f)
        self._food_ids.add(f.id)

    def _eat_food(self, f: Food) -> None:
        self.food.remove(f)
        self._food_ids.discard(f.id)
        self.eaten += 1

    def _update_food(self, dt: float) -> None:
        c = self.config
        if len(self.food) >= c.max_food:
            self._food_acc = 0.0
            return
        self._food_acc += dt * c.food_spawn_rate
        while self._food_acc >= 1.0 and len(self.food) < c.max_food:
            self._food_acc -= 1.0
            self._spawn_food()

    # --- sensing -----------------------------------------------------------

    def _vision_range(self, o: Organism) -> float:
        c = self.config
        return c.vision_base + o.genome.vision * c.vision_range

    def _sense_food(self, o: Organism) -> None:
        """Point `o.target` at the nearest food within vision, or None.

        Toroidal: distances are computed across the wrapped world.
        """
        c = self.config
        range_px = self._vision_range(o)
        r2 = range_px * range_px
        half_w, half_h = c.width / 2, c.height / 2

        best = None
        best_d2 = r2
        for f in self.food:
            dx = f.x - o.x
            if dx > half_w:
                dx -= c.width
            elif dx < -half_w:
                dx += c.width
            if dx * dx > best_d2:
                continue  # early reject on x alone
            dy = f.y - o.y
            if dy > half_h:
                dy -= c.height
            elif dy < -half_h:
                dy += c.height
            d2 = dx * dx + dy * dy
            if d2 < best_d2:
                best_d2 = d2
                best = f
        o.target = best

    # --- behaviour ------------------------------------------------------

    def update(self, dt: float) -> None:
        """Advance the simulation by `dt` seconds."""
        self.time += dt
        c = self.config

        for o in list(self.organisms):
            o.age += dt
            o.readiness += (c.readiness_base + c.readiness_fertility * o.genome.fertility) * dt

            # Decide what to do
            hungry = o.energy < c.hungry_level * c.max_energy

            # Re-scan for food when hungry and the target is missing or
            # stale, throttled to sense_interval so a population with no
            # food in sight cannot scan every tick.
            if hungry and self.time - o.last_sense >= c.sense_interval:
                if o.target is None or o.target.id not in self._food_ids:
                    self._sense_food(o)
                    o.last_sense = self.time

            if hungry and o.target is not None:
                self._steer_toward(o, dt)
            else:
                # Wander: continuously drift the heading by a random amount.
                # Predator behavior (flee) will replace this branch later.
                o.heading += (random.random() - 0.5) * 2 * c.wander_turn_rate * dt

            o.x += math.cos(o.heading) * move_speed_px(o.genome) * dt
            o.y += math.sin(o.heading) * move_speed_px(o.genome) * dt

            # Toroidal world: wrap around the edges instead of hitting walls.
            self._wrap(o)

            o.energy = max(0.0, o.energy - self._drain(o.genome) * dt)
            if o.energy <= 0.0:
                self._kill(o, "starvation")
                continue
            if o.age >= self._max_age(o.genome):
                self._kill(o, "age")
                continue

            # Eat: touching the targeted food
            if o.target is not None and o.target.id in self._food_ids and hungry:
                dx = o.target.x - o.x
                if dx > c.width / 2:
                    dx -= c.width
                elif dx < -c.width / 2:
                    dx += c.width
                dy = o.target.y - o.y
                if dy > c.height / 2:
                    dy -= c.height
                elif dy < -c.height / 2:
                    dy += c.height
                reach = body_radius_px(o.genome.size) + 3
                if dx * dx + dy * dy <= reach * reach:
                    o.energy = min(c.max_energy, o.energy + o.target.energy)
                    self._eat_food(o.target)
                    o.target = None

        self._update_food(dt)
        self.grid.rebuild(self.organisms)
        self._mate()
        self._migrate(dt)

        # Sample the stats graph once per simulated second.
        self._history_acc += dt
        if self._history_acc >= 1.0:
            self._history_acc -= 1.0
            self.history.append(
                (
                    self.time,
                    self.trait_average("speed"),
                    self.trait_average("size"),
                    len(self.organisms),
                )
            )
            if len(self.history) > 300:
                del self.history[0]

    def _steer_toward(self, o: Organism, dt: float) -> None:
        """Turn the heading toward the target at a max rate (toroidal).

        Agility drops with size: big creatures are sluggish.
        """
        c = self.config
        t = o.target
        dx = t.x - o.x
        if dx > c.width / 2:
            dx -= c.width
        elif dx < -c.width / 2:
            dx += c.width
        dy = t.y - o.y
        if dy > c.height / 2:
            dy -= c.height
        elif dy < -c.height / 2:
            dy += c.height

        desired = math.atan2(dy, dx)
        diff = math.atan2(math.sin(desired - o.heading), math.cos(desired - o.heading))
        turn = c.steer_rate * (1.0 - 0.5 * o.genome.size)
        o.heading += max(-turn * dt, min(turn * dt, diff))

    # --- reproduction -----------------------------------------------------

    def _mate(self) -> None:
        """Local mating: a ready, energetic organism pairs with a nearby
        ready partner; the two pay the cost and produce one mutated
        crossover baby at their (toroidal) midpoint.
        """
        c = self.config
        for o in list(self.organisms):
            if len(self.organisms) >= c.max_population:
                break
            if o.readiness < 1.0 or o.energy < c.mate_energy_gate:
                continue
            partner = self._find_partner(o)
            if partner is None:
                continue

            o.energy -= c.mate_cost
            partner.energy -= c.mate_cost
            o.readiness = 0.0
            partner.readiness = 0.0

            # Toroidal midpoint, so a pair straddling an edge still
            # produces a baby between them.
            dx = partner.x - o.x
            if dx > c.width / 2:
                dx -= c.width
            elif dx < -c.width / 2:
                dx += c.width
            dy = partner.y - o.y
            if dy > c.height / 2:
                dy -= c.height
            elif dy < -c.height / 2:
                dy += c.height

            genome = mutate(crossover(o.genome, partner.genome), c.mutation_rate)
            baby = Organism(
                id=self._next_id,
                x=o.x + dx / 2,
                y=o.y + dy / 2,
                heading=random.random() * 2 * math.pi,
                genome=genome,
                energy=c.baby_energy,
                age=0.0,
                generation=max(o.generation, partner.generation) + 1,
            )
            self._next_id += 1
            self._wrap(baby)
            self.organisms.append(baby)
            self.births += 1

    def _find_partner(self, o: Organism) -> Organism | None:
        """First ready, energetic neighbor within the mating radius."""
        c = self.config
        for p in self.grid.within(o.x, o.y, c.mate_radius):
            if p is not o and p.readiness >= 1.0 and p.energy >= c.mate_energy_gate:
                return p
        return None

    # --- trait costs -----------------------------------------------------

    def _drain(self, g: Genome) -> float:
        """Energy per second: metabolism × movement/body upkeep − efficiency."""
        c = self.config
        metabolism = c.base_metabolism + g.metabolism * c.metabolism_range
        upkeep = 1.0 + g.speed * c.speed_cost + g.size * c.size_cost
        saving = 1.0 - g.efficiency * c.efficiency_saving
        return metabolism * upkeep * saving

    def _max_age(self, g: Genome) -> float:
        c = self.config
        return c.base_lifespan + g.lifespan * c.lifespan_range

    # --- observations ----------------------------------------------------

    def trait_average(self, trait: str) -> float:
        """Average of a genome trait across the population, or 0 if empty."""
        pop = self.organisms
        if not pop:
            return 0.0
        return sum(getattr(o.genome, trait) for o in pop) / len(pop)

    # --- helpers ----------------------------------------------------------

    def _migrate(self, dt: float) -> None:
        c = self.config
        if len(self.organisms) >= c.min_population:
            self._migration_acc = 0.0
            return
        self._migration_acc += dt * c.migration_rate
        while self._migration_acc >= 1.0 and len(self.organisms) < c.min_population:
            self._migration_acc -= 1.0
            self._spawn()

    def _wrap(self, o: Organism) -> None:
        c = self.config
        if o.x < 0:
            o.x += c.width
        elif o.x >= c.width:
            o.x -= c.width
        if o.y < 0:
            o.y += c.height
        elif o.y >= c.height:
            o.y -= c.height


# ===== ui/widgets.py =====
"""Tiny hand-drawn UI widgets (pygame draws its own control elements).

These are the building blocks for every panel later: controls sidebar,
organism inspector, experiment picker. Each widget owns its rect, knows
how to draw itself, and returns True from `handle` when it was activated.
"""

import pygame



class Label:
    def __init__(
        self,
        pos: tuple[int, int],
        text: str,
        font: pygame.font.Font,
        color: tuple[int, int, int] = TEXT_DIM,
    ) -> None:
        self.pos = pos  # midleft anchor
        self.font = font
        self.color = color
        self.text = text
        self.surface = font.render(text, True, color)

    def set_text(self, text: str) -> None:
        if text != self.text:
            self.text = text
            self.surface = self.font.render(text, True, self.color)

    def draw(self, surface: pygame.Surface) -> None:
        surface.blit(self.surface, self.surface.get_rect(midleft=self.pos))


class Button:
    def __init__(
        self,
        rect: pygame.Rect | tuple[int, int, int, int],
        label: str,
        font: pygame.font.Font,
    ) -> None:
        self.rect = pygame.Rect(rect)
        self.label = label
        self.font = font
        self._pressed = False

    def handle(self, event: pygame.event.Event) -> bool:
        """Process one event; True when the button was clicked."""
        if event.type == pygame.MOUSEBUTTONDOWN and event.button == 1:
            self._pressed = self.rect.collidepoint(event.pos)
        elif event.type == pygame.MOUSEBUTTONUP and event.button == 1:
            clicked = self._pressed and self.rect.collidepoint(event.pos)
            self._pressed = False
            return clicked
        return False

    def draw(self, surface: pygame.Surface) -> None:
        pygame.draw.rect(surface, PANEL, self.rect, border_radius=6)
        pygame.draw.rect(surface, ACCENT, self.rect, width=1, border_radius=6)
        text = self.font.render(self.label, True, TEXT)
        surface.blit(text, text.get_rect(center=self.rect.center))


class Slider:
    """Horizontal slider; value snapped to `step` increments."""

    def __init__(
        self,
        rect: pygame.Rect | tuple[int, int, int, int],
        font: pygame.font.Font,
        min_value: float,
        max_value: float,
        value: float,
        step: float = 0.25,
    ) -> None:
        self.rect = pygame.Rect(rect)
        self.font = font
        self.min = min_value
        self.max = max_value
        self.step = step
        self._value = value
        self._drag = False

    @property
    def value(self) -> float:
        return self._value

    def _set_from_x(self, x: int) -> None:
        t = max(0.0, min(1.0, (x - self.rect.left) / self.rect.width))
        raw = self.min + t * (self.max - self.min)
        self._value = round(raw / self.step) * self.step

    def _knob_x(self) -> int:
        t = (self._value - self.min) / (self.max - self.min)
        return self.rect.left + round(t * self.rect.width)

    def handle(self, event: pygame.event.Event) -> None:
        if event.type == pygame.MOUSEBUTTONDOWN and event.button == 1:
            self._drag = self.rect.collidepoint(event.pos)
            if self._drag:
                self._set_from_x(event.pos[0])
        elif event.type == pygame.MOUSEMOTION and self._drag:
            self._set_from_x(event.pos[0])
        elif event.type == pygame.MOUSEBUTTONUP and event.button == 1:
            self._drag = False

    def draw(self, surface: pygame.Surface) -> None:
        y = self.rect.centery
        pygame.draw.line(surface, PANEL_BORDER, (self.rect.left, y), (self.rect.right, y), 3)
        knob = self._knob_x()
        if knob > self.rect.left:
            pygame.draw.line(surface, ACCENT, (self.rect.left, y), (knob, y), 3)
        pygame.draw.circle(surface, ACCENT, (knob, y), 6)
        pygame.draw.circle(surface, BG, (knob, y), 2)


# ===== rendering/renderer.py =====
"""Draws the ecosystem onto a pygame surface.

The renderer is a dumb view: it reads simulation state and paints it.
The static background (fill + grid) is pre-rendered once and blitted
every frame, so the per-frame cost is one blit plus the organisms.

Traits are drawn directly, so selection is visible on the plate:
    size       -> body radius
    energy     -> body brightness (dim = starving)
    speed      -> heading tick length
"""

import math

import pygame


GRID_SPACING = 64
STARVED = (30, 90, 62)  # color at zero energy
MAX_TICK = 14  # px at max speed


def _energy_color(energy: float, max_energy: float) -> tuple[int, int, int]:
    t = max(0.0, min(1.0, energy / max_energy))
    return tuple(
        round(starved + (accent - starved) * t)
        for starved, accent in zip(STARVED, ACCENT)
    )


class Renderer:
    def __init__(self, surface: pygame.Surface) -> None:
        self.surface = surface
        self.font = pygame.font.SysFont("dejavusansmono,consolas,monospace", 10)
        w, h = surface.get_size()
        self.background = self._build_background(w, h)

    def _build_background(self, w: int, h: int) -> pygame.Surface:
        bg = pygame.Surface((w, h))
        bg.fill(BG)

        grid = pygame.Surface((w, h), pygame.SRCALPHA)
        for x in range(0, w + 1, GRID_SPACING):
            pygame.draw.line(grid, (*TEXT_DIM, GRID_ALPHA), (x, 0), (x, h))
        for y in range(0, h + 1, GRID_SPACING):
            pygame.draw.line(grid, (*TEXT_DIM, GRID_ALPHA), (0, y), (w, y))
        bg.blit(grid, (0, 0))
        return bg

    def render(self, world: Ecosystem) -> None:
        self.surface.blit(self.background, (0, 0))

        # Food under the organisms
        for f in world.food:
            pygame.draw.circle(self.surface, FOOD, (int(f.x), int(f.y)), 3)

        for o in world.organisms:
            radius = body_radius_px(o.genome.size)
            tick = 4 + o.genome.speed * MAX_TICK  # 4..18 px

            # heading tick: length encodes speed
            pygame.draw.line(
                self.surface,
                HEADING,
                (o.x, o.y),
                (o.x + math.cos(o.heading) * tick,
                 o.y + math.sin(o.heading) * tick),
                1,
            )
            # body: radius encodes size, brightness encodes energy
            pygame.draw.circle(
                self.surface,
                _energy_color(o.energy, world.config.max_energy),
                (int(o.x), int(o.y)),
                round(radius),
            )
            # ready to mate: a thin ring around the body
            if o.readiness >= 1.0:
                pygame.draw.circle(
                    self.surface,
                    ACCENT,
                    (int(o.x), int(o.y)),
                    round(radius) + 2,
                    1,
                )

        self._draw_history(world)

    def _draw_history(self, world: Ecosystem) -> None:
        """Bottom-right sparklines: population (accent) and avg speed (dim)."""
        hist = world.history
        if len(hist) < 2:
            return
        w, h = self.surface.get_size()
        panel = pygame.Rect(w - 196, h - 80, 184, 68)
        pygame.draw.rect(self.surface, PANEL, panel, border_radius=6)
        pygame.draw.rect(self.surface, PANEL_BORDER, panel, width=1, border_radius=6)

        plot = panel.inflate(-12, -30)
        n = len(hist)
        pop_scale = float(world.config.max_population)

        def polyline(key: int, scale: float, color: tuple[int, int, int]) -> None:
            pts = []
            for i, sample in enumerate(hist):
                x = plot.left + (i / (n - 1)) * plot.width
                y = plot.bottom - min(1.0, sample[key] / scale) * plot.height
                pts.append((x, y))
            pygame.draw.lines(self.surface, color, False, pts, 1)

        polyline(3, pop_scale, ACCENT)  # population
        polyline(1, 1.0, TEXT_DIM)  # avg speed

        self.surface.blit(self.font.render("pop", True, ACCENT),
                          (panel.left + 6, panel.bottom - 13))
        self.surface.blit(self.font.render("avg spd", True, TEXT_DIM),
                          (panel.left + 40, panel.bottom - 13))


# ===== main.py =====
"""EvoLab — an artificial ecosystem simulator.

Run:  python main.py
Controls:  Space = pause/resume, mouse = pause button, speed and
mutation-rate sliders.
"""

import argparse
import asyncio
import sys

import pygame


# True under PyScript/Pyodide (WebAssembly) — the browser drives the
# frame timing, so the loop must yield with `await` instead of blocking.
IN_BROWSER = sys.platform == "emscripten"

WIDTH, HEIGHT = 1280, 800

# Fixed simulation step in seconds (60 Hz game-logic tick).
STEP = 1 / 60
# Max steps caught up per frame — prevents the "spiral of death"
# when the window is dragged/backgrounded at high speed.
MAX_STEPS_PER_FRAME = 32

def _load_font(names: str, size: int, bold: bool = False):
    """SysFont on desktop; falls back to pygame's bundled font where
    system fonts are unavailable (e.g. the Pyodide web build)."""
    try:
        f = pygame.font.SysFont(names, size, bold=bold)
        if f is not None:
            return f
    except Exception:
        pass
    return pygame.font.Font(None, size)


async def main() -> int:
    parser = argparse.ArgumentParser(description="EvoLab — artificial ecosystem simulator")
    parser.add_argument(
        "--frames", type=int, default=0,
        help="quit after N rendered frames (0 = run until closed)",
    )
    args = parser.parse_args()

    pygame.init()
    screen = pygame.display.set_mode((WIDTH, HEIGHT))
    font = _load_font("dejavusansmono,consolas,monospace", 14)
    logo_font = _load_font("dejavusans,verdana,sans-serif", 14, bold=True)
    clock = pygame.time.Clock()

    world = Ecosystem(
        WorldConfig(
            width=WIDTH, height=HEIGHT, organisms=80,
            wander_turn_rate=1.6,
        )
    )
    renderer = Renderer(screen)

    # --- header chrome -------------------------------------------------
    header = pygame.Rect(12, 12, WIDTH - 24, 46)
    cy = header.centery
    logo = Label((header.left + 16, cy), "EVOLAB", logo_font, ACCENT)
    population = Label((140, cy), "Population: 80", font)
    food = Label((272, cy), "Food: 0", font)
    generation = Label((362, cy), "Gen: 1", font)
    traits = Label((444, cy), "avg speed 50%  size 50%", font)
    pause_btn = Button((650, cy - 14, 100, 28), "Pause", font)
    mut_label = Label((764, cy), "mut", font, TEXT_DIM)
    mut_slider = Slider((798, cy - 8, 110, 16), font, 0.001, 0.20, 0.05, step=0.001)
    mut_value = Label((914, cy), "5.0%", font)
    speed_value = Label((966, cy), "1.0x", font)
    speed_slider = Slider((1006, cy - 8, 170, 16), font, 0.25, 20.0, 1.0)

    paused = False
    accumulator = 0.0
    frame = 0

    running = True
    while running:
        # dt in seconds, clamped so a long stall doesn't teleport the sim.
        # In the browser the page drives the frame: yield to the event loop
        # and measure elapsed time instead of blocking on the clock.
        if IN_BROWSER:
            await asyncio.sleep(1 / 60)
            dt = min(clock.tick(0) / 1000.0, 0.25)
        else:
            dt = min(clock.tick(60) / 1000.0, 0.25)

        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
            elif event.type == pygame.KEYDOWN and event.key == pygame.K_SPACE:
                paused = not paused
            if pause_btn.handle(event):
                paused = not paused
            speed_slider.handle(event)
            mut_slider.handle(event)

        world.config.mutation_rate = mut_slider.value

        if not paused:
            # fixed timestep with accumulator: speed scales the number of
            # steps per real second, never the size of a step
            accumulator += dt * speed_slider.value
            steps = 0
            while accumulator >= STEP and steps < MAX_STEPS_PER_FRAME:
                world.update(STEP)
                accumulator -= STEP
                steps += 1
            if steps == MAX_STEPS_PER_FRAME:
                accumulator = 0.0  # drop the backlog

        renderer.render(world)

        # --- chrome -----------------------------------------------------
        pygame.draw.rect(screen, PANEL, header, border_radius=8)
        pygame.draw.rect(screen, PANEL_BORDER, header, width=1, border_radius=8)
        population.set_text(f"Population: {len(world.organisms)}")
        food.set_text(f"Food: {len(world.food)}")
        generation.set_text(f"Gen: {max((o.generation for o in world.organisms), default=0)}")
        speed_value.set_text(f"{speed_slider.value:.1f}x")
        mut_value.set_text(f"{mut_slider.value * 100:.1f}%")
        traits.set_text(
            f"avg speed {round(world.trait_average('speed') * 100)}%"
            f"  size {round(world.trait_average('size') * 100)}%"
        )
        logo.draw(screen)
        population.draw(screen)
        food.draw(screen)
        generation.draw(screen)
        traits.draw(screen)
        mut_label.draw(screen)
        mut_slider.draw(screen)
        mut_value.draw(screen)
        speed_value.draw(screen)
        speed_slider.draw(screen)
        pause_btn.draw(screen)

        pygame.display.flip()
        frame += 1
        if args.frames and frame >= args.frames:
            running = False

    pygame.quit()
    return 0


# --- web entry ------------------------------------------------------------
# PyScript executes this file as a script (in an async context), so the
# game is started explicitly: as a task if a loop is already running, or
# via asyncio.run otherwise.
try:
    asyncio.get_running_loop()
    asyncio.create_task(main())
except RuntimeError:
    asyncio.run(main())

try:  # cosmetic: hide the loading line once the game is up
    from pyscript import window as _win

    _status = _win.document.getElementById("status")
    if _status:
        _status.style.display = "none"
except Exception:
    pass
